### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by joeyhub** [djaax/html-webpack-inline-style-plugin#1]
ERROR in   TypeError: callback is not a function

      - index.js:13 compilation.plugin
        [nowork]/[html-webpack-inline-style-plugin]/index.js:13:4

**Comment by djaax** [comment]
Hello, what version of Node.js are you using?

**Comment by joeyhub** [comment]
It's probably more a webpack 4 thing.

**Comment by notdotscott** [comment]
Same issue for me.

Versions:
Node v7.10.1
NPM 4.2.0
Webpack 4.4.1

**Comment by radiocity** [comment]
Bump npm registry plz
